# Generated by Django 4.0.5 on 2022-06-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unique_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.ForeignKey(db_column='bar_code', on_delete=django.db.models.deletion.CASCADE, to='app.bar', to_field='unique_code')),
            ],
        ),
    ]
